In [40]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as seabornInstance
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import pickle

dataset= pd.read_csv('E:\dataset_folder\weather.csv')
print(dataset.shape)

(366, 22)


In [41]:
print("Total Null-values in :\n", dataset.isnull().sum())

Total Null-values in :
 MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64


In [42]:
dataset['Sunshine'].fillna(method='ffill',inplace=True)
dataset.head(100)

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0       8.0     24.3       0.0          3.4       6.3          NW   
1      14.0     26.9       3.6          4.4       9.7         ENE   
2      13.7     23.4       3.6          5.8       3.3          NW   
3      13.3     15.5      39.8          7.2       9.1          NW   
4       7.6     16.1       2.8          5.6      10.6         SSE   
..      ...      ...       ...          ...       ...         ...   
95     18.2     22.6       1.8          8.0       0.0         ENE   
96     16.8     22.8       9.0          2.8       0.3         ESE   
97     13.6     27.4       1.0          2.8       8.0           W   
98     14.5     24.2       0.0          6.8       5.9         SSW   
99     12.4     19.9      16.2          5.4       5.6         ENE   

    WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0            30.0         SW         NW           6.0  ...           29   
1            39.0          E          W           4.0  ...           36   
2            85.0          N        NNE           6.0  ...           69   
3            54.0        WNW          W          30.0  ...           56   
4            50.0        SSE        ESE          20.0  ...           49   
..            ...        ...        ...           ...  ...          ...   
95           33.0        SSE        ENE           7.0  ...           76   
96           30.0          S        SSE           7.0  ...           71   
97           52.0         NW        WNW           6.0  ...           41   
98           61.0          N        NNW          11.0  ...           76   
99           41.0        ESE        ESE           7.0  ...           58   

    Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0        1019.7       1015.0         7         7     14.4     23.6         No   
1        1012.4       1008.4         5         3     17.5     25.7        Yes   
2        1009.5       1007.2         8         7     15.4     20.2        Yes   
3        1005.5       1007.0         2         7     13.5     14.1        Yes   
4        1018.3       1018.5         7         7     11.1     15.4        Yes   
..          ...          ...       ...       ...      ...      ...        ...   
95       1014.4       1011.5         8         8     18.5     22.1        Yes   
96       1010.0       1007.8         8         8     18.4     21.5        Yes   
97       1002.1        997.5         4         7     18.7     26.5         No   
98        999.4        998.9         7         7     17.9     20.3         No   
99       1007.6       1005.0         7         7     13.6     18.7        Yes   

    RISK_MM RainTomorrow  
0       3.6          Yes  
1       3.6          Yes  
2      39.8          Yes  
3       2.8          Yes  
4       0.0           No  
..      ...          ...  
95      9.0          Yes  
96      1.0           No  
97      0.0           No  
98     16.2          Yes  
99      0.0           No  

[100 rows x 22 columns]

In [43]:
print("Total Null-values in :\n" , dataset.isnull().sum())

Total Null-values in :
 MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          0
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64


In [44]:
dataset.drop(dataset.columns[[2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]], axis=1, inplace=True)
print(dataset)


     MinTemp  MaxTemp  Sunshine RainTomorrow
0        8.0     24.3       6.3          Yes
1       14.0     26.9       9.7          Yes
2       13.7     23.4       3.3          Yes
3       13.3     15.5       9.1          Yes
4        7.6     16.1      10.6           No
..       ...      ...       ...          ...
361      9.0     30.7      12.1           No
362      7.1     28.4      12.7           No
363     12.5     19.9       5.3           No
364     12.5     26.9       7.1           No
365     12.3     30.2      12.6           No

[366 rows x 4 columns]


In [45]:
x = dataset.iloc[:,0:3].values
y = dataset.iloc[:,-1].values
print(x)
print(y)

[[ 8.  24.3  6.3]
 [14.  26.9  9.7]
 [13.7 23.4  3.3]
 ...
 [12.5 19.9  5.3]
 [12.5 26.9  7.1]
 [12.3 30.2 12.6]]
['Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes'
 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No'
 'No'

In [46]:
# one_hot_encoded_data = pd.get_dummies(dataset, columns = ['RainTomorrow'])
# print(one_hot_encoded_data)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['RainTomorrow']=le.fit_transform(dataset['RainTomorrow'])
print(dataset)

     MinTemp  MaxTemp  Sunshine  RainTomorrow
0        8.0     24.3       6.3             1
1       14.0     26.9       9.7             1
2       13.7     23.4       3.3             1
3       13.3     15.5       9.1             1
4        7.6     16.1      10.6             0
..       ...      ...       ...           ...
361      9.0     30.7      12.1             0
362      7.1     28.4      12.7             0
363     12.5     19.9       5.3             0
364     12.5     26.9       7.1             0
365     12.3     30.2      12.6             0

[366 rows x 4 columns]


In [47]:
x = dataset.iloc[:,0:3].values
y = dataset.iloc[:,-1].values
print(y)

[1 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1
 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1
 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [48]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [50]:
knn =  KNeighborsClassifier(n_neighbors=5)

In [51]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [52]:
pickle.dump(knn,open('model.pkl','wb'))